sudo: false
language: python
python:
    - '2.7'
    - '2.6'
before_install:
    - git config --global user.email "qetools@f5.com"
    - git config --global user.name "Travis F5 QE Tools"
install:
    - pip install -r requirements_test.txt
script:
    - flake8 --max-complexity=10 .
    - pep257 .
    - py.test tests/test_pytest_symbols.py
    - python setup.py sdist
